import { MenuItem, Review } from './types';

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Chicken Burger',
    description: 'Crispy breast, spicy mayo, iceberg lettuce, and toasted brioche.',
    price: 189,
    category: 'Burgers',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCB01IbC__SPe2xyWUZhLAQYlH0d0b5Pj3Yh2awANu5v2BRzi5PfrYGDX1PcTMlP-j9LZL6xS9wb8l1zpOb73jx2-lfZKdyJHu6yuNSjs44ZsnghccpSSSixjIS3opmkpew8abyer0mcbSvoFPe5kkcULtMj62MgyKFWO1egBdL2MAxTAZG7pUEiZugMFdwjeeCOSVC1fDLCbNgBr4Bsl9vrvVyHj8VMYkPJm3h0DwFzuw7R0YzpnKr4lUWVHrj11Qg2dB5MuiymyM',
    bestSeller: true,
    isVeg: false,
  },
  {
    id: '2',
    name: 'Margherita Pizza',
    description: 'San Marzano tomatoes, fresh mozzarella, and aromatic basil.',
    price: 249,
    category: 'Pizzas',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDMnssdH2gpQ8Yy61CbizsOQP74xHOJoP7Laj7a7jJ1L78GfXScUF9pd1L4m3TKJj_OiNIC7xMYhtjszLpYsDvfpDhgpVIurdvu3J8UsyoD-tQ0gcFTyOWGJ0hZSBnFssKNEPw2oi_cMVBXq8Np8PC5PA4IFAXG4FvokXNwieO3ld6aWea1DLiuDZDxbr9Zm7JUpESrCUoywHwlH5rqw_KyEwQ9oaKTap4bLPY98QPXXYJKz1ydCkHt-WgQCvQ6qKBGiWV0vsUnMOw',
    bestSeller: false,
    isVeg: true,
  },
  {
    id: '3',
    name: 'Mint Mojito',
    description: 'Fresh garden mint, lime, and chilled soda. A Delhi favorite.',
    price: 119,
    category: 'Mojitos',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDo2bS7-xDzYE_JWE6y9fQrJ59qDtg1nMUtXb4rJbd2A7JNsyYZCSZesqKUoc5P2JaAyPl6ksh0P6pb-QMLe966nPH_1d7Yo2rRXTjSEg9Mht2VxRAwyaBR3qEGmCisBy_49lNsu30qEJ75Ba6EsHDGeEwVBl0cYCEIH6qgT22n22DUbpzwggWsWP89TVGEELKvpb9DRkuBprCvVvnNAQtr-M-5xM2bPcqrlagH505J1iVd5Qg8R5vg108nf2dIzfahFHciXz5NeC4',
    bestSeller: false,
    isVeg: true,
  },
  {
    id: '4',
    name: 'Cheese Loaded Fries',
    description: 'Golden fries topped with our signature 3-cheese blend.',
    price: 179,
    category: 'Fries',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB6NgWaXEfJIw689GNqTxhS7vbAgzXtHXXvy6VxvQNNlcVKJoe3CZr6LDKBSGKYaw4sQuQl0eXhVDAI0Vw7V4fXlSDs3kZ5JeSf-uvLNwUCrdM1cpDHgYpXrfUiXkL3QTrURT0Zz3gAWjXQeWY3WD5jbOLWPVdW57kJZtS4kCHfxf3gi1KVlRGaqsqj1F8j86pZOCo-2bhvBZedYQazIMjkNTPP5-5AcI2vpNaWT_fRj-oSbxSDydUnaWDoG_-ABjbvk2COO5mkyHs',
    bestSeller: true,
    isVeg: true,
  },
  {
    id: '5',
    name: 'Family Cave Combo',
    description: '2 Burgers + Large Pizza + Fries + 4 Drinks. The ultimate Delhi feast.',
    price: 999,
    category: 'Combos',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDi69tx6ZDtv0KLtEXFCjDe3V8eexTpfvkwQveGL32tR7mGRhadIv-c7Ijh-3KcMbX6S0H9YFxpefEugdCyLIrHmKlA_ladOSOtELqPbEoHd1LF7JUwvwbMiUuqoEH_jyTlLcnjWTGakg2hEQT2aO4OyPDWwgFdImS4xSr4h8mCtQZA0G5ViN22HsLz4uFdtTKaaVbQynRvJHVTBB9ZZIJWGD3SK6uN-CC3MiVM3luv5hM95KrRJNd4XxakNwgBD_TplZW2sihI5gk',
    bestSeller: true,
    isVeg: false,
  },
  {
    id: '6',
    name: 'Pizza + Mojito Combo',
    description: 'Your favorite Margherita pizza paired with a refreshing Mint Mojito.',
    price: 449,
    category: 'Combos',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCFJHkp2BGpfGfcHJggGutGrm4ZrjGp5tK2sRL7SZkcfrTxFX_-VRbHtE-f38psQ-Qqx3YweXIr4VZGz_6_GObRbXqL1SdzGSthJotrANunTfjvdz_C223bR3z0beZLCImTy7UB4T-9p-YT_57s5LMnt1jncZKHv5gK5mhXktIr3Gve3Rv3ilj5M67v59cIRp3lHh2VivkNjoGYluCco1ojMz73wCRJEoedn73MNOrws5cfVHZGKiQVT4qjOJ09dIE-NqbTBJ2dfWk',
    bestSeller: false,
    isVeg: true,
  },
  {
    id: '7',
    name: 'Extreme Veggie Paradise Pizza',
    description: 'Overloaded with jalapenos, bell peppers, golden corn, baby corn and black olives.',
    price: 299,
    category: 'Pizzas',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXxf6vBVYvSFQIdfMDZJo2SvoKyXqN_I_O178DmrqvcIXMOznEUMKEvTIs3ksC6FyVqwNeUVWtRd2CFKpU1nhaTGuRvl0Kp5scMi3tfrQA-N00JEk0toCs__chhSeeNYj71Gh8LHMUo-8Bkgp-EUbNhM1HXfKNMG9SMhhigdxqrxhiL5YjtwcOjAh1o7to2mxC9COKYNRLfbqB-UyO6h7tT3Mn2uwVQ3cXP1KkR_KJlu5G_Q1yWV7lMCnnfegJh4K3qwaiOKV1oz0',
    bestSeller: true,
    isVeg: true,
  },
  {
    id: '8',
    name: 'Volcano Bacon & Cheese Burger',
    description: 'Molten cheddar over a flame-grilled custom chicken patty seasoned with hickory spices.',
    price: 219,
    category: 'Burgers',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBX0qY3Fyd6Btj-pvsh1_WUvPUiXkMzWJcLDTnytYFpS4RJO4nrTLszABYdDKe2jf61QuK-eh7r2Si7ubPR6DNB_-iy-6Esffd8zglgS1vDWYz10V_jvrAuevCMnRiKgQU6gaBfplfKmgg5xQwJdt0OcoA3FCoKXGcg24IRSJfS_BWd15oOT9UuF8XUTw2gbtkMw5VoWmwrjLH-91_J_AmFN5Aar18BBh0IFWA2bufarlShzcmJpx3KrdqovDfMGWT9dT8nvksE0OA',
    bestSeller: false,
    isVeg: false,
  },
  {
    id: '9',
    name: 'Creamy Mushroom Alfredo Pasta',
    description: 'Fresh fettuccine tossed in dynamic roasted garlic white wine & parmesan cream sauce.',
    price: 239,
    category: 'Pasta',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAHl6XwceBstfqT_c3EwAdv_e9r-ZqVPpjO0zuC_LfgXg-Z3turXOv7O6JqdN9St8al_a6CSXkbg0-RiqPdvqLpGiM5xyMXIKDk75TC4LckrMrHvZu9qg6aV0qTSF4IPRUS1dyOcB6UMNAj1VxUEyzbw2_5y90kXCmyt_wCVF4W_1wcfhHNnqX3GwzPbZDSm8s4AtNu94bjlD84OOi0j53ZSOw7BitLbZGxgrKQKUfsxBvHkjs7gqLbUnnN7aFWsWgzHs2iBvSAZSs',
    bestSeller: false,
    isVeg: true,
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'r1',
    author: 'Rohan Gupta',
    text: 'Finally, the best chicken burger in Yamuna Vihar! The mojitos are genuinely fresh, not just sweet syrup!',
    rating: 5,
    avatarColor: 'bg-orange-500',
    date: '2026-06-11',
  },
  {
    id: 'r2',
    author: 'Anjali Sharma',
    text: 'Margherita pizza here is a true masterpiece. Delicate, hot woodfired-style crust with premium cheese.',
    rating: 5,
    avatarColor: 'bg-yellow-500',
    date: '2026-06-10',
  },
  {
    id: 'r3',
    author: 'Divyansh Singh',
    text: 'Delivered in 20 minutes hot and steamy in B-block. The Cheese Loaded Fries are a meal by themselves. Incredible value!',
    rating: 5,
    avatarColor: 'bg-rose-500',
    date: '2026-06-08',
  },
];
